export interface Phase {
  label: string
  weeks: number[]
  color: string
  bg: string
  tip: string
}

export interface Exercise {
  id: string
  name: string
  rest: string
  muscle: string
  w: string
  /** 12 entries, one per microcycle. Format: "sets×reps|note" */
  m: string[]
}

export interface Day {
  id: string
  num: number
  name: string
  icon: string
  color: string
  focus: string
  warmup: string[]
  exercises: Exercise[]
  finisher: string | null
}

export interface Program {
  phases: Phase[]
  days: Day[]
}

export const PROGRAM: Program = {
  phases: [
    {
      label: 'Adaptación / Técnica',
      weeks: [1, 2, 3],
      color: '#43e97b',
      bg: 'rgba(67,233,123,0.15)',
      tip: 'Cargas manejables, RIR 2-1. Enfócate en aprender la técnica. Progresión de +1 rep/semana.',
    },
    {
      label: 'Volumen Base',
      weeks: [4, 5, 6, 7],
      color: '#6c63ff',
      bg: 'rgba(108,99,255,0.15)',
      tip: 'Sube carga al inicio del bloque (+5-10%). Las semanas siguientes mantén. Las series aumentan gradualmente.',
    },
    {
      label: 'Bloque de Fuerza',
      weeks: [8, 9],
      color: '#fd9644',
      bg: 'rgba(253,150,68,0.15)',
      tip: 'Cargas pesadas, pocas reps (4-6), RIR 1. Más series. Descansa bien entre series (2-3 min).',
    },
    {
      label: 'Hipertrofia',
      weeks: [10, 11],
      color: '#ff6584',
      bg: 'rgba(255,101,132,0.15)',
      tip: 'Reps moderadas con técnicas de intensidad: tempo 3" excéntrico, pausas 1-2", parciales.',
    },
    {
      label: 'Descarga',
      weeks: [12],
      color: '#f9ca24',
      bg: 'rgba(249,202,36,0.15)',
      tip: 'Reduce carga -5%. Menos volumen. Sin ir al fallo. El cuerpo se superkompensa esta semana.',
    },
  ],
  days: [
    {
      id: 'torsoA',
      num: 1,
      name: 'Torso A',
      icon: '💪',
      color: '#6c63ff',
      focus: 'Pecho · Espalda · Hombros · Brazos',
      warmup: [
        'Rotaciones hombro con banda 3×8',
        'Aducción escapular con banda 3×8',
        'Retracción escapular colgado 3×6',
        'Crunch ABD 4×10',
      ],
      exercises: [
        {
          id: 'torsoA_ex0',
          name: 'Press Banca Plano',
          rest: '2 min',
          muscle: 'Pecho',
          w: '95 kg',
          m: [
            '3×10|RIR 2-1, carga técnica',
            '3×11|Misma carga S1',
            '3×12|Misma carga',
            '3×10|⬆ +5% carga (+2.5kg)',
            '3×8|Carga S4',
            '3×9|Mantener carga',
            '3×10|Mantener carga',
            '3×8|⬆ Subir carga',
            '4×6|Mantener carga',
            '4×7|Mantener carga',
            '4×8|Mantener carga',
            '3×6|⬇ -5% (descarga)',
          ],
        },
        {
          id: 'torsoA_ex1',
          name: 'Press Inclinado Mancuerna',
          rest: '2 min',
          muscle: 'Pecho clavicular',
          w: '30 kg',
          m: [
            '3×10|RIR 2-1, carga manejable',
            '3×11|Mantener carga',
            '3×12|Igual carga',
            '3×10|⬆ +2.5kg',
            '3×8|Usar carga RIR 2-1',
            '3×9|Mantener carga',
            '3×10|Mantener carga',
            '3×10|⬇ -5% carga',
            '4×6|⬆ Aumentar carga S7',
            '4×7|Mantener carga',
            '4×8|Mantener carga',
            '4×6|Aumentar carga',
          ],
        },
        {
          id: 'torsoA_ex2',
          name: 'Remo "T"',
          rest: "1'30\"",
          muscle: 'Espalda media',
          w: '70 kg',
          m: [
            '4×12|RIR 2-1, enfoque técnica',
            '4×10|⬆ +5% carga',
            '4×11|Mantener carga',
            '4×12|Mantener carga',
            '4×8|⬆ Aumento carga ligera',
            '4×9|Mantener carga',
            '4×10|Mantener carga',
            '4×10|⬇ -5% carga',
            '5×5|⬆ Aumento ligero carga',
            '5×6|Mantener carga',
            '5×7|Mantener carga',
            '5×5|⬆ Aumento ligero',
          ],
        },
        {
          id: 'torsoA_ex3',
          name: 'Elevaciones Laterales',
          rest: "1'30\"",
          muscle: 'Deltoides lateral',
          w: '12.5 kg',
          m: [
            '3×10|Carga manejable RIR 2-1',
            '3×11|Mantener carga',
            '3×12|Mantener carga',
            '3×10|⬆ Aumento ligero carga',
            '3×10|Mantener, 1" pausa arriba',
            '3×11-12|Mantener, 1" pausa',
            '3×8|⬆ Aumento carga',
            '4×8|Mantener carga',
            '4×9|Mantener carga',
            '4×6+10P|Última serie: +10 parciales',
            '4×7|3" bajada · 1" arriba',
            '4×8-10|Progresión de reps',
          ],
        },
        {
          id: 'torsoA_ex4',
          name: 'Bíceps Martillo + Ext. Tríceps Polea',
          rest: "1'30\"",
          muscle: 'Bíceps · Tríceps',
          w: '60 / 50',
          m: [
            '3×8|Carga manejable RIR 2-1',
            '3×8|Misma carga',
            '3×9|Misma carga',
            '3×9|Mantener carga',
            '3×8|⬆ Aumento ligero',
            '3×9|Mantener carga',
            '3×10|Mantener carga',
            '4×8|⬆ Subir carga',
            '4×6|⬆ +5% carga',
            '4×7|Mantener carga',
            '4×8|Mantener carga',
            '4×8|⬇ -5% carga',
          ],
        },
      ],
      finisher: 'Cardio 15 min — Intensidad media (RPE 5)',
    },
    {
      id: 'piernaA',
      num: 2,
      name: 'Pierna A',
      icon: '🦵',
      color: '#43e97b',
      focus: 'Cuádriceps · Glúteo · Isquios · Gemelos',
      warmup: [
        'Balanceo Front/Lat piernas 2×10',
        'Rotación interna cadera en suelo 3×8',
        'Hip Opener con KB 2×6',
        'Curl Nórdico 3×5',
      ],
      exercises: [
        {
          id: 'piernaA_ex0',
          name: 'Sentadilla Hack',
          rest: '2-3 min',
          muscle: 'Cuádriceps',
          w: '90 kg',
          m: [
            '3×10|Carga manejable, técnica',
            '3×10|Misma carga',
            '3×11|Misma carga',
            '3×12|Control y técnica',
            '4×6|RIR 2-1',
            '4×9|Mantener carga',
            '4×6|⬆ Mejorar carga S5',
            '4×7|Mantener carga',
            '5×5|⬆ +5% carga',
            '4×6|Mantener carga',
            '5×5|⬆ Mejorar carga S9',
            '3×8|Carga S11 (descarga)',
          ],
        },
        {
          id: 'piernaA_ex1',
          name: 'Prensa 45°',
          rest: '2 min',
          muscle: 'Cuád · Glúteo',
          w: '200 kg',
          m: [
            '3×10|Peso manejable RIR 2-1',
            '3×11|Mantener carga',
            '3×12|Mantener carga',
            '3×8|⬆ +10% carga',
            '4×6|Mantener carga',
            '3×9-10|Igual carga',
            '4×6|⬆ Mejorar carga',
            '4×7-8|Mantener carga',
            '4×9|Mantener carga',
            '5×5|⬆ +10% carga',
            '5×6|Mantener carga',
            '4×6|Igual carga',
          ],
        },
        {
          id: 'piernaA_ex2',
          name: 'Leg Extension',
          rest: "1'30\"",
          muscle: 'Cuádriceps',
          w: '50 kg',
          m: [
            '3×8-10|Volumen base, técnica',
            '3×8-10|Misma carga',
            '3×9-11|Misma carga',
            '3×9-11|Misma carga',
            '3×9-11|⬆ Aumentar carga',
            '4×6-8|Aumentar carga',
            '4×6-8|Mantener carga',
            '4×8-10|Mantener carga',
            '4×8-10|Mantener carga',
            '3×8-10|Mantener carga',
            '3×8-10|⬆ Mejorar carga S1',
            '4×8|Mantener carga',
          ],
        },
        {
          id: 'piernaA_ex3',
          name: 'Patada Glúteo Polea',
          rest: "1'30\"",
          muscle: 'Glúteo',
          w: '— (elegir)',
          m: [
            '3×10-12|Carga controlada',
            '3×10-12|Mantener',
            '3×10-12|Mantener',
            '4×10-12|Mantener',
            '4×10-12|Mantener',
            '4×10-12|Mantener',
            '4×10-12|Mantener',
            '4×12-15|Aumentar reps',
            '4×12-15|Mantener',
            '4×12-15|Mantener',
            '4×12-15|Mantener',
            '4×12-15|Mantener',
          ],
        },
        {
          id: 'piernaA_ex4',
          name: 'Leg Curl Sentado',
          rest: '2 min',
          muscle: 'Isquiosurales',
          w: '40 kg',
          m: [
            '3×8-10|Volumen base, control excéntrica',
            '3×8-10|Mantener',
            '3×9-11|Mantener',
            '3×9-11|Mantener',
            '3×9-11|Mantener',
            '4×6-8|Mantener',
            '4×6-8|Mantener',
            '4×8-10|Mantener',
            '4×8-10|Mantener',
            '4×8-9|Mantener',
            '4×8-9|⬆ Mejorar carga S1',
            '4×10|Mantener',
          ],
        },
        {
          id: 'piernaA_ex5',
          name: 'Gemelo en Prensa',
          rest: "1'30\"",
          muscle: 'Gastrocnemio',
          w: '100 kg',
          m: [
            '4×12|Volumen base, técnica',
            '4×12|⬆ +10% carga',
            '4×12|Mantener',
            '4×15|Mantener',
            '4×8|⬆ Subir 10%',
            '4×9|Mantener',
            '4×10|Mantener',
            '4×11-12|Igual carga',
            '4×10|⬆ Subir carga',
            '4×10|1" pausa arriba',
            '4×12|Igual carga',
            '4×14|Igual carga',
          ],
        },
      ],
      finisher: null,
    },
    {
      id: 'torsoB',
      num: 3,
      name: 'Torso B',
      icon: '🔥',
      color: '#fd9644',
      focus: 'Espalda · Hombros · Pecho · Bíceps · Tríceps',
      warmup: [
        'Rotaciones hombro con banda 2×10',
        'Elevaciones Lat/Front con banda 2×8',
        'Retracción Escapular con Banda 3×6',
        'Twist Ruso con KB 3×10',
        'Plancha ISO 3×40"',
      ],
      exercises: [
        {
          id: 'torsoB_ex0',
          name: 'Jalón Polea al Pecho',
          rest: '2-3 min',
          muscle: 'Dorsal ancho',
          w: '70 kg',
          m: [
            '3×10-12|RIR 2-1, base técnica',
            '3×10-12|Mantener',
            '3×10-12|Mantener',
            '3×8-10|⬆ Subir carga',
            '3×8-10|Mantener',
            '4×8|Mantener',
            '4×9|Mantener',
            '4×10|Mantener',
            '4×8|⬆ Mejorar carga',
            '5×7|Mantener',
            '4×9|Mantener',
            '4×10|Mantener',
          ],
        },
        {
          id: 'torsoB_ex1',
          name: 'Remo Gironda Máquina (agarre neutro)',
          rest: '2 min',
          muscle: 'Espalda media',
          w: '70 kg',
          m: [
            '3×8|Base técnica, vol medio',
            '3×9|Mantener',
            '3×10|Mantener',
            '3×11|⬆ Subir carga',
            '4×8|Mantener',
            '4×9|Mantener',
            '4×10|⬆ Subir carga',
            '5×6|Mantener',
            '5×7|Mantener',
            '5×8|3" en bajada',
            '4×10|Mantener',
            '4×11|Mantener',
          ],
        },
        {
          id: 'torsoB_ex2',
          name: 'Press Militar Mancuerna',
          rest: "1'30\"",
          muscle: 'Deltoides frontal',
          w: '25 kg',
          m: [
            '3×8|RIR 2-1, base técnica',
            '3×9|Mantener',
            '3×10|Mantener',
            '5×5|⬆ +Carga ligera RIR 1',
            '4×8|Carga semana anterior',
            '4×9|Mantener',
            '4×10|Mantener',
            '6×4|⬆ Carga pesada RIR 1',
            '4×6|Carga anterior',
            '4×7|Mantener',
            '4×7|Mantener',
            '5×3|⬆ Carga pesada RIR 1',
          ],
        },
        {
          id: 'torsoB_ex3',
          name: 'Cruce en Polea',
          rest: "1'30\"",
          muscle: 'Pecho aislamiento',
          w: '30 kg',
          m: [
            '3×12|Carga controlada, técnica',
            '3×13|Mantener',
            '3×15|Mantener',
            '3×10|⬆ Subir 1 placa',
            '3×11|Mantener',
            '3×12|Mantener',
            '3×15|Mantener',
            '3×12|2" pausa al contraer',
            '4×8|⬆ Mejorar carga S1',
            '4×9|Mantener',
            '4×10|Mantener',
            '4×10|Mantener',
          ],
        },
        {
          id: 'torsoB_ex4',
          name: 'Curl Bíceps Barra',
          rest: "1'30\"",
          muscle: 'Bíceps',
          w: '40 kg',
          m: [
            '3×8|RIR 2-1, volumen técnico',
            '3×9|Mantener',
            '3×10|Mantener',
            '5×5|⬆ Subir carga RIR 1',
            '4×6|Carga S4',
            '4×7|Mantener',
            '4×8|Mantener',
            '6×4|⬆ Carga RIR 1',
            '4×5|Carga S8',
            '4×6|Mantener',
            '4×7|Mantener',
            '5×5|⬆ Subir carga ligera',
          ],
        },
        {
          id: 'torsoB_ex5',
          name: 'Press Francés Barra (Skull Crusher)',
          rest: "1'30\"",
          muscle: 'Tríceps',
          w: '— (elegir)',
          m: [
            '3×10|ROM completo, técnica',
            '3×11|Mantener',
            '3×12|Mantener',
            '5×5|⬆ +5% carga',
            '4×8|Mantener',
            '4×9|Mantener',
            '4×10|Mantener',
            '5×4|⬆ Subir carga 5%',
            '4×6|Mantener',
            '4×7|Mantener',
            '4×8|Mantener',
            '4×8|3" en excéntrica',
          ],
        },
      ],
      finisher: 'Cardio 15 min — Intensidad media (RPE 5-6)',
    },
    {
      id: 'piernaB',
      num: 4,
      name: 'Pierna B',
      icon: '⚡',
      color: '#ff6584',
      focus: 'Isquios · Glúteo · Abductor · Soleo · Brazos',
      warmup: [
        'Bicicleta 5 min suave',
        'Rotación externa-interna cadera 2×8',
        'Extens. Cadera Banco Romano',
        'Squat ISO 90° 3×30"',
      ],
      exercises: [
        {
          id: 'piernaB_ex0',
          name: 'RDL Barra (Peso Muerto Rumano)',
          rest: '2-3 min',
          muscle: 'Isquios · Glúteo',
          w: '— (elegir)',
          m: [
            '3×8|Base técnica, ROM completo',
            '3×9|Base técnica',
            '3×10|Base técnica',
            '5×5|⬆ Subir carga',
            '4×6|Misma carga',
            '4×7|Mantener',
            '4×8|Mantener',
            '5×4|⬆ Subir carga',
            '4×5|Mantener',
            '4×6|Mantener',
            '5×3|⬆ Subir carga S8',
            '4×5|Carga S11',
          ],
        },
        {
          id: 'piernaB_ex1',
          name: 'Leg Curl Tumbado',
          rest: '2 min',
          muscle: 'Isquiosurales',
          w: '— (elegir)',
          m: [
            '3×10|Volumen base, técnica',
            '3×11|Mantener',
            '3×12|Mantener',
            '5×6|⬆ Subir 1-2 placas',
            '4×10|Mantener',
            '4×11|Mantener',
            '4×12|Mantener',
            '6×5|⬆ Subir 1-2 placas',
            '4×8|Mantener',
            '4×9|Mantener',
            '4×10|3" en excéntrica',
            '—|Descanso / opcional',
          ],
        },
        {
          id: 'piernaB_ex2',
          name: 'Estocadas (Lunges)',
          rest: '2 min',
          muscle: 'Glúteo · Cuádriceps',
          w: '— (elegir)',
          m: [
            '4×6|RIR 2-1, base técnica',
            '4×6|Misma carga',
            '4×6|Subida explosiva',
            '3×8|⬆ Subir carga',
            '3×9|Mantener',
            '3×10|Mantener',
            '4×8|Mantener',
            '3×6|⬆ Carga pesada',
            '4×6|Mantener',
            '5×5|⬆ Subir carga ligera',
            '3×10|Carga S4',
            '2×10|Mantener',
          ],
        },
        {
          id: 'piernaB_ex3',
          name: 'Abductor Máquina',
          rest: "1'30\"",
          muscle: 'Glúteo medio',
          w: '— (elegir)',
          m: [
            '4×10-12|Técnica y ROM',
            '4×10-12|1" pausa concéntrica',
            '4×10-12|Mantener',
            '4×10-12|⬆ Subir carga',
            '4×10-12|Mantener',
            '4×10-12|Mantener',
            '4×10-12|Mantener',
            '4×12-15|Mantener',
            '4×12-15|Mantener',
            '4×10|⬆ Subir carga',
            '4×12|Mantener',
            '3×10|Mantener',
          ],
        },
        {
          id: 'piernaB_ex4',
          name: 'Soleo en Máquina',
          rest: "1'30\"",
          muscle: 'Soleo',
          w: '— (elegir)',
          m: [
            '4×12|2-3" en bajada',
            '4×12|Bajada en 2-3"',
            '4×10|⬆ Aumento carga ligera',
            '4×12|Mantener',
            '4×15|Mantener',
            '4×15|Mantener',
            '4×18|Mantener',
            '4×12|⬆ Subir carga',
            '4×14|Mantener',
            '4×18|Mantener',
            '4×20|Mantener',
            '4×10|Mantener',
          ],
        },
        {
          id: 'piernaB_ex5',
          name: 'Ext. Tríceps Trasnuca + Curl Mancuerna',
          rest: "1'30\"",
          muscle: 'Tríceps · Bíceps',
          w: '— (elegir)',
          m: [
            '3×10-12|Carga controlada',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
            '3×10-12|Misma carga',
          ],
        },
      ],
      finisher: 'Cardio 15 min — Intensidad media (RPE 5-6)',
    },
  ],
}

// ─── YouTube lookup for warmup exercises ────────────────────────────────────

const WU_YT: Record<string, string> = {
  'Rotaciones hombro con banda':    'rotaciones hombro banda elastica movilidad calentamiento',
  'Aducción escapular':              'aduccion escapular banda ejercicio movilidad',
  'Retracción escapular colgado':    'retraccion escapular colgado barra dominadas',
  'Retraccion Escapular con Banda':  'retraccion escapular banda elastica ejercicio',
  'Crunch ABD':                      'crunch abdominal tecnica correcta core',
  'Balanceo Front':                  'balanceo piernas calentamiento movilidad cadera',
  'Rotación interna cadera':         'rotacion interna cadera suelo movilidad hip',
  'Rotacion externa':                'rotacion externa interna cadera movilidad cadera',
  'Hip Opener':                      'hip opener kettlebell movilidad cadera',
  'Curl Nórdico':                    'curl nordico isquiotibiales ejercicio tecnica',
  'Elevaciones  Lat':                'elevaciones laterales frontales banda calentamiento hombro',
  'Elevaciones Lat':                 'elevaciones laterales frontales banda calentamiento hombro',
  'Twist Ruso':                      'twist ruso kettlebell oblicuos core',
  'Plancha ISO':                     'plancha isometrica core tecnica correcta',
  'Bicicleta':                       'bicicleta estatica calentamiento cardio suave',
  'Extens. Cadera Banco Romano':     'extension cadera banco romano gluteo ejercicio',
  'Squat ISO':                       'squat isometrico wall sit 90 grados cadera',
}

export function getWarmupYouTubeUrl(name: string): string | null {
  for (const key in WU_YT) {
    if (name.toLowerCase().includes(key.toLowerCase())) {
      return `https://www.youtube.com/results?search_query=${encodeURIComponent(WU_YT[key])}`
    }
  }
  return null
}

export function getPhase(micro: number): Phase {
  return PROGRAM.phases.find(p => p.weeks.includes(micro)) ?? PROGRAM.phases[0]
}

export function getDayBySlug(slug: string): Day | undefined {
  return PROGRAM.days.find(d => d.id === slug)
}

export function parsePrescription(raw: string): { sets: string; note: string } {
  const [sets, note = ''] = raw.split('|')
  return { sets, note }
}

export const EXERCISE_WIKI_SLUG: Record<string, string> = {
  'torsoA_ex0': 'Bench_press',
  'torsoA_ex1': 'Fly_(exercise)',
  'torsoA_ex2': 'Bent-over_row',
  'torsoA_ex3': 'Lateral_raise',
  'torsoA_ex4': 'Hammer_curl',
  'piernaA_ex0': 'Squat_(exercise)',
  'piernaA_ex1': 'Leg_press',
  'piernaA_ex2': 'Leg_extension_(exercise)',
  'piernaA_ex3': 'Hip_extension',
  'piernaA_ex4': 'Leg_curl',
  'piernaA_ex5': 'Calf_raise',
  'torsoB_ex0': 'Lat_pulldown',
  'torsoB_ex1': 'Bent-over_row',
  'torsoB_ex2': 'Overhead_press',
  'torsoB_ex3': 'Fly_(exercise)',
  'torsoB_ex4': 'Biceps_curl',
  'torsoB_ex5': 'Triceps_extension',
  'piernaB_ex0': 'Romanian_deadlift',
  'piernaB_ex1': 'Leg_curl',
  'piernaB_ex2': 'Lunge',
  'piernaB_ex3': 'Hip_abduction',
  'piernaB_ex4': 'Calf_raise',
  'piernaB_ex5': 'Triceps_extension',
}
